/* tslint:disable */
/* eslint-disable */
/**
 * Report Service
 * Manages report templates, execution, history, and scheduling. Uses PostgreSQL for relations and Elasticsearch for analytic report data.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ReportTemplate,
  TemplateRequest,
} from '../models/index';
import {
    ReportTemplateFromJSON,
    ReportTemplateToJSON,
    TemplateRequestFromJSON,
    TemplateRequestToJSON,
} from '../models/index';

export interface ExecuteIdPostRequest {
    id: number;
}

export interface RootPostRequest {
    templateRequest: TemplateRequest;
}

/**
 * 
 */
export class ReportsApi extends runtime.BaseAPI {

    /**
     * Creates request options for executeIdPost without sending the request
     */
    async executeIdPostRequestOpts(requestParameters: ExecuteIdPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling executeIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/execute/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Execute a report template
     */
    async executeIdPostRaw(requestParameters: ExecuteIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.executeIdPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Execute a report template
     */
    async executeIdPost(requestParameters: ExecuteIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.executeIdPostRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for rootGet without sending the request
     */
    async rootGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all report templates
     */
    async rootGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ReportTemplate>>> {
        const requestOptions = await this.rootGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ReportTemplateFromJSON));
    }

    /**
     * Get all report templates
     */
    async rootGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ReportTemplate>> {
        const response = await this.rootGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rootPost without sending the request
     */
    async rootPostRequestOpts(requestParameters: RootPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['templateRequest'] == null) {
            throw new runtime.RequiredError(
                'templateRequest',
                'Required parameter "templateRequest" was null or undefined when calling rootPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TemplateRequestToJSON(requestParameters['templateRequest']),
        };
    }

    /**
     * Create a new report template
     */
    async rootPostRaw(requestParameters: RootPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.rootPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a new report template
     */
    async rootPost(requestParameters: RootPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.rootPostRaw(requestParameters, initOverrides);
    }

}
