/* tslint:disable */
/* eslint-disable */
/**
 * Report Service
 * Manages report templates, execution, history, and scheduling. Uses PostgreSQL for relations and Elasticsearch for analytic report data.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ScheduleRequest,
} from '../models/index';
import {
    ScheduleRequestFromJSON,
    ScheduleRequestToJSON,
} from '../models/index';

export interface SchedulesPostRequest {
    scheduleRequest: ScheduleRequest;
}

/**
 * 
 */
export class SchedulesApi extends runtime.BaseAPI {

    /**
     * Creates request options for schedulesPost without sending the request
     */
    async schedulesPostRequestOpts(requestParameters: SchedulesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['scheduleRequest'] == null) {
            throw new runtime.RequiredError(
                'scheduleRequest',
                'Required parameter "scheduleRequest" was null or undefined when calling schedulesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/schedules`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleRequestToJSON(requestParameters['scheduleRequest']),
        };
    }

    /**
     * Create a new report schedule
     */
    async schedulesPostRaw(requestParameters: SchedulesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.schedulesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a new report schedule
     */
    async schedulesPost(requestParameters: SchedulesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.schedulesPostRaw(requestParameters, initOverrides);
    }

}
