/* tslint:disable */
/* eslint-disable */
/**
 * Report Service
 * Manages report templates, execution, history, and scheduling. Uses PostgreSQL for relations and Elasticsearch for analytic report data.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReportTemplate
 */
export interface ReportTemplate {
    /**
     * 
     * @type {number}
     * @memberof ReportTemplate
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ReportTemplate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportTemplate
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportTemplate
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof ReportTemplate
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the ReportTemplate interface.
 */
export function instanceOfReportTemplate(value: object): value is ReportTemplate {
    return true;
}

export function ReportTemplateFromJSON(json: any): ReportTemplate {
    return ReportTemplateFromJSONTyped(json, false);
}

export function ReportTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'description': json['description'] == null ? undefined : json['description'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ReportTemplateToJSON(json: any): ReportTemplate {
    return ReportTemplateToJSONTyped(json, false);
}

export function ReportTemplateToJSONTyped(value?: ReportTemplate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': value['type'],
        'description': value['description'],
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

