/* tslint:disable */
/* eslint-disable */
/**
 * Report Service
 * Manages report templates, execution, history, and scheduling. Uses PostgreSQL for relations and Elasticsearch for analytic report data.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScheduleRequest
 */
export interface ScheduleRequest {
    /**
     * 
     * @type {number}
     * @memberof ScheduleRequest
     */
    reportId: number;
    /**
     * 
     * @type {string}
     * @memberof ScheduleRequest
     */
    cronExpression: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ScheduleRequest
     */
    emails?: Array<string>;
}

/**
 * Check if a given object implements the ScheduleRequest interface.
 */
export function instanceOfScheduleRequest(value: object): value is ScheduleRequest {
    if (!('reportId' in value) || value['reportId'] === undefined) return false;
    if (!('cronExpression' in value) || value['cronExpression'] === undefined) return false;
    return true;
}

export function ScheduleRequestFromJSON(json: any): ScheduleRequest {
    return ScheduleRequestFromJSONTyped(json, false);
}

export function ScheduleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reportId': json['reportId'],
        'cronExpression': json['cronExpression'],
        'emails': json['emails'] == null ? undefined : json['emails'],
    };
}

export function ScheduleRequestToJSON(json: any): ScheduleRequest {
    return ScheduleRequestToJSONTyped(json, false);
}

export function ScheduleRequestToJSONTyped(value?: ScheduleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reportId': value['reportId'],
        'cronExpression': value['cronExpression'],
        'emails': value['emails'],
    };
}

