/* tslint:disable */
/* eslint-disable */
/**
 * Report Service
 * Manages report templates, execution, history, and scheduling. Uses PostgreSQL for relations and Elasticsearch for analytic report data.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplateRequest
 */
export interface TemplateRequest {
    /**
     * 
     * @type {string}
     * @memberof TemplateRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateRequest
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the TemplateRequest interface.
 */
export function instanceOfTemplateRequest(value: object): value is TemplateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function TemplateRequestFromJSON(json: any): TemplateRequest {
    return TemplateRequestFromJSONTyped(json, false);
}

export function TemplateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function TemplateRequestToJSON(json: any): TemplateRequest {
    return TemplateRequestToJSONTyped(json, false);
}

export function TemplateRequestToJSONTyped(value?: TemplateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'description': value['description'],
    };
}

