/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.reportforge.form.controller;

import com.reportforge.form.model.FormDefinition;
import com.reportforge.form.model.FormRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")
@Validated
@Tag(name = "Forms", description = "the Forms API")
public interface DefaultApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_ROOT_GET = "/";
    /**
     * GET / : Get all forms
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "rootGet",
        summary = "Get all forms",
        tags = { "Forms" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = FormDefinition.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = DefaultApi.PATH_ROOT_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<List<FormDefinition>> rootGet(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"description\" : \"description\", \"id\" : \"id\", \"title\" : \"title\", \"fields\" : [ \"{}\", \"{}\" ] }, { \"description\" : \"description\", \"id\" : \"id\", \"title\" : \"title\", \"fields\" : [ \"{}\", \"{}\" ] } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_ROOT_POST = "/";
    /**
     * POST / : Create a new dynamic form
     *
     * @param formRequest  (required)
     * @return Created (status code 201)
     */
    @Operation(
        operationId = "rootPost",
        summary = "Create a new dynamic form",
        tags = { "Forms" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = DefaultApi.PATH_ROOT_POST,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> rootPost(
        @Parameter(name = "FormRequest", description = "", required = true) @Valid @RequestBody FormRequest formRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
