/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.reportforge.form.controller;

import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")
@Validated
@Tag(name = "Submissions", description = "the Submissions API")
public interface FormIdApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_FORM_ID_SUBMISSIONS_GET = "/{formId}/submissions";
    /**
     * GET /{formId}/submissions : Get responses for a specific form
     *
     * @param formId  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "formIdSubmissionsGet",
        summary = "Get responses for a specific form",
        tags = { "Submissions" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Object.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = FormIdApi.PATH_FORM_ID_SUBMISSIONS_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<List<Object>> formIdSubmissionsGet(
        @NotNull @Parameter(name = "formId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("formId") String formId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ \"{}\", \"{}\" ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_FORM_ID_SUBMISSIONS_POST = "/{formId}/submissions";
    /**
     * POST /{formId}/submissions : Submit a response to a form
     *
     * @param formId  (required)
     * @param body  (required)
     * @return Submission saved (status code 201)
     */
    @Operation(
        operationId = "formIdSubmissionsPost",
        summary = "Submit a response to a form",
        tags = { "Submissions" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Submission saved")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = FormIdApi.PATH_FORM_ID_SUBMISSIONS_POST,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> formIdSubmissionsPost(
        @NotNull @Parameter(name = "formId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("formId") String formId,
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody Object body
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
