/* tslint:disable */
/* eslint-disable */
/**
 * Data Source Service
 * Manages external database connections and acts as a proxy to query remote databases securely.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataSourceRequest
 */
export interface DataSourceRequest {
    /**
     * 
     * @type {string}
     * @memberof DataSourceRequest
     */
    name: string;
    /**
     * 
     * @type {DataSourceRequestTypeEnum}
     * @memberof DataSourceRequest
     */
    type: DataSourceRequestTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof DataSourceRequest
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof DataSourceRequest
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof DataSourceRequest
     */
    password?: string;
}


/**
 * @export
 */
export const DataSourceRequestTypeEnum = {
    Postgres: 'POSTGRES',
    Mysql: 'MYSQL',
    Mongodb: 'MONGODB',
    Sqlserver: 'SQLSERVER',
    Elasticsearch: 'ELASTICSEARCH'
} as const;
export type DataSourceRequestTypeEnum = typeof DataSourceRequestTypeEnum[keyof typeof DataSourceRequestTypeEnum];


/**
 * Check if a given object implements the DataSourceRequest interface.
 */
export function instanceOfDataSourceRequest(value: object): value is DataSourceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function DataSourceRequestFromJSON(json: any): DataSourceRequest {
    return DataSourceRequestFromJSONTyped(json, false);
}

export function DataSourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataSourceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'url': json['url'],
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function DataSourceRequestToJSON(json: any): DataSourceRequest {
    return DataSourceRequestToJSONTyped(json, false);
}

export function DataSourceRequestToJSONTyped(value?: DataSourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'url': value['url'],
        'username': value['username'],
        'password': value['password'],
    };
}

