/* tslint:disable */
/* eslint-disable */
/**
 * Data Source Service
 * Manages external database connections and acts as a proxy to query remote databases securely.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataSourceConfig
 */
export interface DataSourceConfig {
    /**
     * 
     * @type {number}
     * @memberof DataSourceConfig
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DataSourceConfig
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DataSourceConfig
     */
    type?: string;
    /**
     * Obfuscated or partial URL for display
     * @type {string}
     * @memberof DataSourceConfig
     */
    url?: string;
    /**
     * 
     * @type {DataSourceConfigStatusEnum}
     * @memberof DataSourceConfig
     */
    status?: DataSourceConfigStatusEnum;
}


/**
 * @export
 */
export const DataSourceConfigStatusEnum = {
    Connected: 'CONNECTED',
    Failed: 'FAILED',
    Pending: 'PENDING'
} as const;
export type DataSourceConfigStatusEnum = typeof DataSourceConfigStatusEnum[keyof typeof DataSourceConfigStatusEnum];


/**
 * Check if a given object implements the DataSourceConfig interface.
 */
export function instanceOfDataSourceConfig(value: object): value is DataSourceConfig {
    return true;
}

export function DataSourceConfigFromJSON(json: any): DataSourceConfig {
    return DataSourceConfigFromJSONTyped(json, false);
}

export function DataSourceConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataSourceConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'url': json['url'] == null ? undefined : json['url'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function DataSourceConfigToJSON(json: any): DataSourceConfig {
    return DataSourceConfigToJSONTyped(json, false);
}

export function DataSourceConfigToJSONTyped(value?: DataSourceConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': value['type'],
        'url': value['url'],
        'status': value['status'],
    };
}

