/* tslint:disable */
/* eslint-disable */
/**
 * Data Source Service
 * Manages external database connections and acts as a proxy to query remote databases securely.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IdQueryPostRequest
 */
export interface IdQueryPostRequest {
    /**
     * 
     * @type {string}
     * @memberof IdQueryPostRequest
     */
    sql?: string;
}

/**
 * Check if a given object implements the IdQueryPostRequest interface.
 */
export function instanceOfIdQueryPostRequest(value: object): value is IdQueryPostRequest {
    return true;
}

export function IdQueryPostRequestFromJSON(json: any): IdQueryPostRequest {
    return IdQueryPostRequestFromJSONTyped(json, false);
}

export function IdQueryPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdQueryPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sql': json['sql'] == null ? undefined : json['sql'],
    };
}

export function IdQueryPostRequestToJSON(json: any): IdQueryPostRequest {
    return IdQueryPostRequestToJSONTyped(json, false);
}

export function IdQueryPostRequestToJSONTyped(value?: IdQueryPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sql': value['sql'],
    };
}

