/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard Service
 * Manages dashboard layouts, configured widgets, KPI tracking, and user preferences stored in Elasticsearch.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Dashboard,
  DashboardRequest,
} from '../models/index';
import {
    DashboardFromJSON,
    DashboardToJSON,
    DashboardRequestFromJSON,
    DashboardRequestToJSON,
} from '../models/index';

export interface IdGetRequest {
    id: string;
}

export interface RootPostRequest {
    dashboardRequest: DashboardRequest;
}

/**
 * 
 */
export class DashboardsApi extends runtime.BaseAPI {

    /**
     * Creates request options for idGet without sending the request
     */
    async idGetRequestOpts(requestParameters: IdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling idGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a specific dashboard config
     */
    async idGetRaw(requestParameters: IdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Dashboard>> {
        const requestOptions = await this.idGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DashboardFromJSON(jsonValue));
    }

    /**
     * Get a specific dashboard config
     */
    async idGet(requestParameters: IdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Dashboard> {
        const response = await this.idGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rootGet without sending the request
     */
    async rootGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all dashboards for user
     */
    async rootGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Dashboard>>> {
        const requestOptions = await this.rootGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DashboardFromJSON));
    }

    /**
     * Get all dashboards for user
     */
    async rootGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Dashboard>> {
        const response = await this.rootGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rootPost without sending the request
     */
    async rootPostRequestOpts(requestParameters: RootPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['dashboardRequest'] == null) {
            throw new runtime.RequiredError(
                'dashboardRequest',
                'Required parameter "dashboardRequest" was null or undefined when calling rootPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DashboardRequestToJSON(requestParameters['dashboardRequest']),
        };
    }

    /**
     * Create a new dashboard
     */
    async rootPostRaw(requestParameters: RootPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.rootPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a new dashboard
     */
    async rootPost(requestParameters: RootPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.rootPostRaw(requestParameters, initOverrides);
    }

}
