/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.reportforge.gateway.api;

import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")
@Validated
@Tag(name = "Routing", description = "the Routing API")
public interface DashboardsApi {

    String PATH_DASHBOARDS_GET = "/dashboards/**";
    /**
     * GET /dashboards/** : Routes to Dashboard Service
     *
     * @return Successful routing (status code 200)
     */
    @Operation(
        operationId = "dashboardsGet",
        summary = "Routes to Dashboard Service",
        tags = { "Routing" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful routing")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = DashboardsApi.PATH_DASHBOARDS_GET
    )
    ResponseEntity<Void> dashboardsGet(
        
    );

}
