/* tslint:disable */
/* eslint-disable */
/**
 * Form Service
 * Dynamic form builder and submission storage mapping forms to Elasticsearch indices.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FormDefinition
 */
export interface FormDefinition {
    /**
     * 
     * @type {string}
     * @memberof FormDefinition
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof FormDefinition
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof FormDefinition
     */
    description?: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof FormDefinition
     */
    fields?: Array<object>;
}

/**
 * Check if a given object implements the FormDefinition interface.
 */
export function instanceOfFormDefinition(value: object): value is FormDefinition {
    return true;
}

export function FormDefinitionFromJSON(json: any): FormDefinition {
    return FormDefinitionFromJSONTyped(json, false);
}

export function FormDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'fields': json['fields'] == null ? undefined : json['fields'],
    };
}

export function FormDefinitionToJSON(json: any): FormDefinition {
    return FormDefinitionToJSONTyped(json, false);
}

export function FormDefinitionToJSONTyped(value?: FormDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'fields': value['fields'],
    };
}

