/* tslint:disable */
/* eslint-disable */
/**
 * Form Service
 * Dynamic form builder and submission storage mapping forms to Elasticsearch indices.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FormRequest
 */
export interface FormRequest {
    /**
     * 
     * @type {string}
     * @memberof FormRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof FormRequest
     */
    description?: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof FormRequest
     */
    fields?: Array<object>;
}

/**
 * Check if a given object implements the FormRequest interface.
 */
export function instanceOfFormRequest(value: object): value is FormRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function FormRequestFromJSON(json: any): FormRequest {
    return FormRequestFromJSONTyped(json, false);
}

export function FormRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'fields': json['fields'] == null ? undefined : json['fields'],
    };
}

export function FormRequestToJSON(json: any): FormRequest {
    return FormRequestToJSONTyped(json, false);
}

export function FormRequestToJSONTyped(value?: FormRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'fields': value['fields'],
    };
}

