/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard Service
 * Manages dashboard layouts, configured widgets, KPI tracking, and user preferences stored in Elasticsearch.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DashboardRequest
 */
export interface DashboardRequest {
    /**
     * 
     * @type {string}
     * @memberof DashboardRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DashboardRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the DashboardRequest interface.
 */
export function instanceOfDashboardRequest(value: object): value is DashboardRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function DashboardRequestFromJSON(json: any): DashboardRequest {
    return DashboardRequestFromJSONTyped(json, false);
}

export function DashboardRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function DashboardRequestToJSON(json: any): DashboardRequest {
    return DashboardRequestToJSONTyped(json, false);
}

export function DashboardRequestToJSONTyped(value?: DashboardRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

