/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard Service
 * Manages dashboard layouts, configured widgets, KPI tracking, and user preferences stored in Elasticsearch.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Dashboard
 */
export interface Dashboard {
    /**
     * 
     * @type {string}
     * @memberof Dashboard
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Dashboard
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Dashboard
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof Dashboard
     */
    ownerId?: number;
    /**
     * JSON representing the UI layout structure
     * @type {object}
     * @memberof Dashboard
     */
    layout?: object;
    /**
     * 
     * @type {Array<object>}
     * @memberof Dashboard
     */
    widgets?: Array<object>;
}

/**
 * Check if a given object implements the Dashboard interface.
 */
export function instanceOfDashboard(value: object): value is Dashboard {
    return true;
}

export function DashboardFromJSON(json: any): Dashboard {
    return DashboardFromJSONTyped(json, false);
}

export function DashboardFromJSONTyped(json: any, ignoreDiscriminator: boolean): Dashboard {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'ownerId': json['ownerId'] == null ? undefined : json['ownerId'],
        'layout': json['layout'] == null ? undefined : json['layout'],
        'widgets': json['widgets'] == null ? undefined : json['widgets'],
    };
}

export function DashboardToJSON(json: any): Dashboard {
    return DashboardToJSONTyped(json, false);
}

export function DashboardToJSONTyped(value?: Dashboard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'ownerId': value['ownerId'],
        'layout': value['layout'],
        'widgets': value['widgets'],
    };
}

