/* tslint:disable */
/* eslint-disable */
/**
 * Data Source Service
 * Manages external database connections and acts as a proxy to query remote databases securely.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DataSourceConfig,
  DataSourceRequest,
} from '../models/index';
import {
    DataSourceConfigFromJSON,
    DataSourceConfigToJSON,
    DataSourceRequestFromJSON,
    DataSourceRequestToJSON,
} from '../models/index';

export interface RootPostRequest {
    dataSourceRequest: DataSourceRequest;
}

/**
 * 
 */
export class DataSourcesApi extends runtime.BaseAPI {

    /**
     * Creates request options for rootGet without sending the request
     */
    async rootGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get configured data sources
     */
    async rootGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DataSourceConfig>>> {
        const requestOptions = await this.rootGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DataSourceConfigFromJSON));
    }

    /**
     * Get configured data sources
     */
    async rootGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DataSourceConfig>> {
        const response = await this.rootGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rootPost without sending the request
     */
    async rootPostRequestOpts(requestParameters: RootPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['dataSourceRequest'] == null) {
            throw new runtime.RequiredError(
                'dataSourceRequest',
                'Required parameter "dataSourceRequest" was null or undefined when calling rootPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DataSourceRequestToJSON(requestParameters['dataSourceRequest']),
        };
    }

    /**
     * Configure a new data source
     */
    async rootPostRaw(requestParameters: RootPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.rootPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Configure a new data source
     */
    async rootPost(requestParameters: RootPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.rootPostRaw(requestParameters, initOverrides);
    }

}
