/* tslint:disable */
/* eslint-disable */
/**
 * Data Source Service
 * Manages external database connections and acts as a proxy to query remote databases securely.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  IdQueryPostRequest,
} from '../models/index';
import {
    IdQueryPostRequestFromJSON,
    IdQueryPostRequestToJSON,
} from '../models/index';

export interface IdQueryPostOperationRequest {
    id: number;
    idQueryPostRequest: IdQueryPostRequest;
}

/**
 * 
 */
export class QueryApi extends runtime.BaseAPI {

    /**
     * Creates request options for idQueryPost without sending the request
     */
    async idQueryPostRequestOpts(requestParameters: IdQueryPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling idQueryPost().'
            );
        }

        if (requestParameters['idQueryPostRequest'] == null) {
            throw new runtime.RequiredError(
                'idQueryPostRequest',
                'Required parameter "idQueryPostRequest" was null or undefined when calling idQueryPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{id}/query`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IdQueryPostRequestToJSON(requestParameters['idQueryPostRequest']),
        };
    }

    /**
     * Execute a query against a remote data source
     */
    async idQueryPostRaw(requestParameters: IdQueryPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<object>>> {
        const requestOptions = await this.idQueryPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Execute a query against a remote data source
     */
    async idQueryPost(requestParameters: IdQueryPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<object>> {
        const response = await this.idQueryPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
