/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway Service
 * Handles routing, load balancing, CORS, and rate limiting for the ReportForge platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * 
 */
export class RoutingApi extends runtime.BaseAPI {

    /**
     * Creates request options for authGet without sending the request
     */
    async authGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/**`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Routes to Auth Service
     */
    async authGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.authGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Routes to Auth Service
     */
    async authGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authGetRaw(initOverrides);
    }

    /**
     * Creates request options for dashboardsGet without sending the request
     */
    async dashboardsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/dashboards/**`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Routes to Dashboard Service
     */
    async dashboardsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.dashboardsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Routes to Dashboard Service
     */
    async dashboardsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.dashboardsGetRaw(initOverrides);
    }

    /**
     * Creates request options for dataSourceGet without sending the request
     */
    async dataSourceGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/data-source/**`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Routes to Data Source Service
     */
    async dataSourceGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.dataSourceGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Routes to Data Source Service
     */
    async dataSourceGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.dataSourceGetRaw(initOverrides);
    }

    /**
     * Creates request options for formsGet without sending the request
     */
    async formsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/forms/**`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Routes to Form Service
     */
    async formsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.formsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Routes to Form Service
     */
    async formsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.formsGetRaw(initOverrides);
    }

    /**
     * Creates request options for reportsGet without sending the request
     */
    async reportsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/reports/**`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Routes to Report Service
     */
    async reportsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.reportsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Routes to Report Service
     */
    async reportsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.reportsGetRaw(initOverrides);
    }

}
