/* tslint:disable */
/* eslint-disable */
/**
 * Auth & User Service
 * Centralized identity management. Handles login, registration, and RBAC via JWT.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JwtResponse
 */
export interface JwtResponse {
    /**
     * 
     * @type {string}
     * @memberof JwtResponse
     */
    token?: string;
    /**
     * 
     * @type {string}
     * @memberof JwtResponse
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof JwtResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof JwtResponse
     */
    username?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof JwtResponse
     */
    roles?: Array<string>;
}

/**
 * Check if a given object implements the JwtResponse interface.
 */
export function instanceOfJwtResponse(value: object): value is JwtResponse {
    return true;
}

export function JwtResponseFromJSON(json: any): JwtResponse {
    return JwtResponseFromJSONTyped(json, false);
}

export function JwtResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JwtResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'] == null ? undefined : json['username'],
        'roles': json['roles'] == null ? undefined : json['roles'],
    };
}

export function JwtResponseToJSON(json: any): JwtResponse {
    return JwtResponseToJSONTyped(json, false);
}

export function JwtResponseToJSONTyped(value?: JwtResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'type': value['type'],
        'id': value['id'],
        'username': value['username'],
        'roles': value['roles'],
    };
}

