/* tslint:disable */
/* eslint-disable */
/**
 * Form Service
 * Dynamic form builder and submission storage mapping forms to Elasticsearch indices.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FormDefinition,
  FormRequest,
} from '../models/index';
import {
    FormDefinitionFromJSON,
    FormDefinitionToJSON,
    FormRequestFromJSON,
    FormRequestToJSON,
} from '../models/index';

export interface RootPostRequest {
    formRequest: FormRequest;
}

/**
 * 
 */
export class FormsApi extends runtime.BaseAPI {

    /**
     * Creates request options for rootGet without sending the request
     */
    async rootGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all forms
     */
    async rootGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FormDefinition>>> {
        const requestOptions = await this.rootGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FormDefinitionFromJSON));
    }

    /**
     * Get all forms
     */
    async rootGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FormDefinition>> {
        const response = await this.rootGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rootPost without sending the request
     */
    async rootPostRequestOpts(requestParameters: RootPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['formRequest'] == null) {
            throw new runtime.RequiredError(
                'formRequest',
                'Required parameter "formRequest" was null or undefined when calling rootPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FormRequestToJSON(requestParameters['formRequest']),
        };
    }

    /**
     * Create a new dynamic form
     */
    async rootPostRaw(requestParameters: RootPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.rootPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a new dynamic form
     */
    async rootPost(requestParameters: RootPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.rootPostRaw(requestParameters, initOverrides);
    }

}
