/* tslint:disable */
/* eslint-disable */
/**
 * Form Service
 * Dynamic form builder and submission storage mapping forms to Elasticsearch indices.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface FormIdSubmissionsGetRequest {
    formId: string;
}

export interface FormIdSubmissionsPostRequest {
    formId: string;
    body: object;
}

/**
 * 
 */
export class SubmissionsApi extends runtime.BaseAPI {

    /**
     * Creates request options for formIdSubmissionsGet without sending the request
     */
    async formIdSubmissionsGetRequestOpts(requestParameters: FormIdSubmissionsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['formId'] == null) {
            throw new runtime.RequiredError(
                'formId',
                'Required parameter "formId" was null or undefined when calling formIdSubmissionsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/{formId}/submissions`;
        urlPath = urlPath.replace(`{${"formId"}}`, encodeURIComponent(String(requestParameters['formId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get responses for a specific form
     */
    async formIdSubmissionsGetRaw(requestParameters: FormIdSubmissionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<object>>> {
        const requestOptions = await this.formIdSubmissionsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get responses for a specific form
     */
    async formIdSubmissionsGet(requestParameters: FormIdSubmissionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<object>> {
        const response = await this.formIdSubmissionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for formIdSubmissionsPost without sending the request
     */
    async formIdSubmissionsPostRequestOpts(requestParameters: FormIdSubmissionsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['formId'] == null) {
            throw new runtime.RequiredError(
                'formId',
                'Required parameter "formId" was null or undefined when calling formIdSubmissionsPost().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling formIdSubmissionsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/{formId}/submissions`;
        urlPath = urlPath.replace(`{${"formId"}}`, encodeURIComponent(String(requestParameters['formId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Submit a response to a form
     */
    async formIdSubmissionsPostRaw(requestParameters: FormIdSubmissionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.formIdSubmissionsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Submit a response to a form
     */
    async formIdSubmissionsPost(requestParameters: FormIdSubmissionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.formIdSubmissionsPostRaw(requestParameters, initOverrides);
    }

}
